// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod pcodec {

#[allow(unused_imports, dead_code)]
pub mod naegling {


pub enum NaeChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NaeChunk<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for NaeChunk<'a> {
  type Inner = NaeChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NaeChunk<'a> {
  pub const VT_QUANTIZATION: ::flatbuffers::VOffsetT = 4;
  pub const VT_WEIGHTS: ::flatbuffers::VOffsetT = 6;
  pub const VT_BIASES: ::flatbuffers::VOffsetT = 8;
  pub const VT_PCO_META: ::flatbuffers::VOffsetT = 10;
  pub const VT_PCO_PAGE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    NaeChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NaeChunkArgs<'args>
  ) -> ::flatbuffers::WIPOffset<NaeChunk<'bldr>> {
    let mut builder = NaeChunkBuilder::new(_fbb);
    if let Some(x) = args.pco_page { builder.add_pco_page(x); }
    if let Some(x) = args.pco_meta { builder.add_pco_meta(x); }
    if let Some(x) = args.biases { builder.add_biases(x); }
    if let Some(x) = args.weights { builder.add_weights(x); }
    builder.add_quantization(args.quantization);
    builder.finish()
  }


  #[inline]
  pub fn quantization(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NaeChunk::VT_QUANTIZATION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn weights(&self) -> Option<::flatbuffers::Vector<'a, i16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i16>>>(NaeChunk::VT_WEIGHTS, None)}
  }
  #[inline]
  pub fn biases(&self) -> Option<::flatbuffers::Vector<'a, i16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i16>>>(NaeChunk::VT_BIASES, None)}
  }
  #[inline]
  pub fn pco_meta(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(NaeChunk::VT_PCO_META, None)}
  }
  #[inline]
  pub fn pco_page(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(NaeChunk::VT_PCO_PAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for NaeChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("quantization", Self::VT_QUANTIZATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i16>>>("weights", Self::VT_WEIGHTS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i16>>>("biases", Self::VT_BIASES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("pco_meta", Self::VT_PCO_META, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("pco_page", Self::VT_PCO_PAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct NaeChunkArgs<'a> {
    pub quantization: u32,
    pub weights: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i16>>>,
    pub biases: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i16>>>,
    pub pco_meta: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub pco_page: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for NaeChunkArgs<'a> {
  #[inline]
  fn default() -> Self {
    NaeChunkArgs {
      quantization: 0,
      weights: None,
      biases: None,
      pco_meta: None,
      pco_page: None,
    }
  }
}

pub struct NaeChunkBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> NaeChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_quantization(&mut self, quantization: u32) {
    self.fbb_.push_slot::<u32>(NaeChunk::VT_QUANTIZATION, quantization, 0);
  }
  #[inline]
  pub fn add_weights(&mut self, weights: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NaeChunk::VT_WEIGHTS, weights);
  }
  #[inline]
  pub fn add_biases(&mut self, biases: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NaeChunk::VT_BIASES, biases);
  }
  #[inline]
  pub fn add_pco_meta(&mut self, pco_meta: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NaeChunk::VT_PCO_META, pco_meta);
  }
  #[inline]
  pub fn add_pco_page(&mut self, pco_page: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NaeChunk::VT_PCO_PAGE, pco_page);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> NaeChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NaeChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<NaeChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for NaeChunk<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("NaeChunk");
      ds.field("quantization", &self.quantization());
      ds.field("weights", &self.weights());
      ds.field("biases", &self.biases());
      ds.field("pco_meta", &self.pco_meta());
      ds.field("pco_page", &self.pco_page());
      ds.finish()
  }
}
pub enum NaeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Nae<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Nae<'a> {
  type Inner = Nae<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Nae<'a> {
  pub const VT_H: ::flatbuffers::VOffsetT = 4;
  pub const VT_W: ::flatbuffers::VOffsetT = 6;
  pub const VT_C: ::flatbuffers::VOffsetT = 8;
  pub const VT_CHUNK_H: ::flatbuffers::VOffsetT = 10;
  pub const VT_CHUNK_W: ::flatbuffers::VOffsetT = 12;
  pub const VT_PCO_HEADER: ::flatbuffers::VOffsetT = 14;
  pub const VT_CHUNKS: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Nae { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NaeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Nae<'bldr>> {
    let mut builder = NaeBuilder::new(_fbb);
    if let Some(x) = args.chunks { builder.add_chunks(x); }
    if let Some(x) = args.pco_header { builder.add_pco_header(x); }
    builder.add_chunk_w(args.chunk_w);
    builder.add_chunk_h(args.chunk_h);
    builder.add_c(args.c);
    builder.add_w(args.w);
    builder.add_h(args.h);
    builder.finish()
  }


  #[inline]
  pub fn h(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Nae::VT_H, Some(0)).unwrap()}
  }
  #[inline]
  pub fn w(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Nae::VT_W, Some(0)).unwrap()}
  }
  #[inline]
  pub fn c(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Nae::VT_C, Some(0)).unwrap()}
  }
  #[inline]
  pub fn chunk_h(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Nae::VT_CHUNK_H, Some(0)).unwrap()}
  }
  #[inline]
  pub fn chunk_w(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Nae::VT_CHUNK_W, Some(0)).unwrap()}
  }
  #[inline]
  pub fn pco_header(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Nae::VT_PCO_HEADER, None)}
  }
  #[inline]
  pub fn chunks(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<NaeChunk<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<NaeChunk>>>>(Nae::VT_CHUNKS, None)}
  }
}

impl ::flatbuffers::Verifiable for Nae<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("h", Self::VT_H, false)?
     .visit_field::<u32>("w", Self::VT_W, false)?
     .visit_field::<u32>("c", Self::VT_C, false)?
     .visit_field::<u32>("chunk_h", Self::VT_CHUNK_H, false)?
     .visit_field::<u32>("chunk_w", Self::VT_CHUNK_W, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("pco_header", Self::VT_PCO_HEADER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<NaeChunk>>>>("chunks", Self::VT_CHUNKS, false)?
     .finish();
    Ok(())
  }
}
pub struct NaeArgs<'a> {
    pub h: u32,
    pub w: u32,
    pub c: u32,
    pub chunk_h: u32,
    pub chunk_w: u32,
    pub pco_header: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub chunks: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<NaeChunk<'a>>>>>,
}
impl<'a> Default for NaeArgs<'a> {
  #[inline]
  fn default() -> Self {
    NaeArgs {
      h: 0,
      w: 0,
      c: 0,
      chunk_h: 0,
      chunk_w: 0,
      pco_header: None,
      chunks: None,
    }
  }
}

pub struct NaeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> NaeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_h(&mut self, h: u32) {
    self.fbb_.push_slot::<u32>(Nae::VT_H, h, 0);
  }
  #[inline]
  pub fn add_w(&mut self, w: u32) {
    self.fbb_.push_slot::<u32>(Nae::VT_W, w, 0);
  }
  #[inline]
  pub fn add_c(&mut self, c: u32) {
    self.fbb_.push_slot::<u32>(Nae::VT_C, c, 0);
  }
  #[inline]
  pub fn add_chunk_h(&mut self, chunk_h: u32) {
    self.fbb_.push_slot::<u32>(Nae::VT_CHUNK_H, chunk_h, 0);
  }
  #[inline]
  pub fn add_chunk_w(&mut self, chunk_w: u32) {
    self.fbb_.push_slot::<u32>(Nae::VT_CHUNK_W, chunk_w, 0);
  }
  #[inline]
  pub fn add_pco_header(&mut self, pco_header: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Nae::VT_PCO_HEADER, pco_header);
  }
  #[inline]
  pub fn add_chunks(&mut self, chunks: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<NaeChunk<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Nae::VT_CHUNKS, chunks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> NaeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NaeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Nae<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Nae<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Nae");
      ds.field("h", &self.h());
      ds.field("w", &self.w());
      ds.field("c", &self.c());
      ds.field("chunk_h", &self.chunk_h());
      ds.field("chunk_w", &self.chunk_w());
      ds.field("pco_header", &self.pco_header());
      ds.field("chunks", &self.chunks());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Nae`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_nae_unchecked`.
pub fn root_as_nae(buf: &[u8]) -> Result<Nae<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Nae>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Nae` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_nae_unchecked`.
pub fn size_prefixed_root_as_nae(buf: &[u8]) -> Result<Nae<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Nae>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Nae` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_nae_unchecked`.
pub fn root_as_nae_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Nae<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Nae<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Nae` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_nae_unchecked`.
pub fn size_prefixed_root_as_nae_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Nae<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Nae<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Nae and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Nae`.
pub unsafe fn root_as_nae_unchecked(buf: &[u8]) -> Nae<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Nae>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Nae and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Nae`.
pub unsafe fn size_prefixed_root_as_nae_unchecked(buf: &[u8]) -> Nae<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Nae>(buf) }
}
#[inline]
pub fn finish_nae_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Nae<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_nae_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Nae<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Naegling
}  // pub mod Pcodec

