// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod pcodec {

#[allow(unused_imports, dead_code)]
pub mod naegling {


pub enum HeaderOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Header<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Header<'a> {
  type Inner = Header<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Header<'a> {
  pub const VT_H: ::flatbuffers::VOffsetT = 4;
  pub const VT_W: ::flatbuffers::VOffsetT = 6;
  pub const VT_C: ::flatbuffers::VOffsetT = 8;
  pub const VT_CHUNK_H: ::flatbuffers::VOffsetT = 10;
  pub const VT_CHUNK_W: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Header { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args HeaderArgs
  ) -> ::flatbuffers::WIPOffset<Header<'bldr>> {
    let mut builder = HeaderBuilder::new(_fbb);
    builder.add_chunk_w(args.chunk_w);
    builder.add_chunk_h(args.chunk_h);
    builder.add_c(args.c);
    builder.add_w(args.w);
    builder.add_h(args.h);
    builder.finish()
  }


  #[inline]
  pub fn h(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Header::VT_H, Some(0)).unwrap()}
  }
  #[inline]
  pub fn w(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Header::VT_W, Some(0)).unwrap()}
  }
  #[inline]
  pub fn c(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Header::VT_C, Some(0)).unwrap()}
  }
  #[inline]
  pub fn chunk_h(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Header::VT_CHUNK_H, Some(0)).unwrap()}
  }
  #[inline]
  pub fn chunk_w(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Header::VT_CHUNK_W, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Header<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("h", Self::VT_H, false)?
     .visit_field::<u32>("w", Self::VT_W, false)?
     .visit_field::<u32>("c", Self::VT_C, false)?
     .visit_field::<u32>("chunk_h", Self::VT_CHUNK_H, false)?
     .visit_field::<u32>("chunk_w", Self::VT_CHUNK_W, false)?
     .finish();
    Ok(())
  }
}
pub struct HeaderArgs {
    pub h: u32,
    pub w: u32,
    pub c: u32,
    pub chunk_h: u32,
    pub chunk_w: u32,
}
impl<'a> Default for HeaderArgs {
  #[inline]
  fn default() -> Self {
    HeaderArgs {
      h: 0,
      w: 0,
      c: 0,
      chunk_h: 0,
      chunk_w: 0,
    }
  }
}

pub struct HeaderBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HeaderBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_h(&mut self, h: u32) {
    self.fbb_.push_slot::<u32>(Header::VT_H, h, 0);
  }
  #[inline]
  pub fn add_w(&mut self, w: u32) {
    self.fbb_.push_slot::<u32>(Header::VT_W, w, 0);
  }
  #[inline]
  pub fn add_c(&mut self, c: u32) {
    self.fbb_.push_slot::<u32>(Header::VT_C, c, 0);
  }
  #[inline]
  pub fn add_chunk_h(&mut self, chunk_h: u32) {
    self.fbb_.push_slot::<u32>(Header::VT_CHUNK_H, chunk_h, 0);
  }
  #[inline]
  pub fn add_chunk_w(&mut self, chunk_w: u32) {
    self.fbb_.push_slot::<u32>(Header::VT_CHUNK_W, chunk_w, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> HeaderBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    HeaderBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Header<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Header<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Header");
      ds.field("h", &self.h());
      ds.field("w", &self.w());
      ds.field("c", &self.c());
      ds.field("chunk_h", &self.chunk_h());
      ds.field("chunk_w", &self.chunk_w());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Header`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_header_unchecked`.
pub fn root_as_header(buf: &[u8]) -> Result<Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Header>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Header` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_header_unchecked`.
pub fn size_prefixed_root_as_header(buf: &[u8]) -> Result<Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Header>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Header` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_header_unchecked`.
pub fn root_as_header_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Header<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Header` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_header_unchecked`.
pub fn size_prefixed_root_as_header_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Header<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Header and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Header`.
pub unsafe fn root_as_header_unchecked(buf: &[u8]) -> Header<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Header>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Header and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Header`.
pub unsafe fn size_prefixed_root_as_header_unchecked(buf: &[u8]) -> Header<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Header>(buf) }
}
#[inline]
pub fn finish_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Header<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Header<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Naegling
}  // pub mod Pcodec

