[package]
name = "pco_java"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
half = { version = "2.0.0" }
jni = "0.21.1"
pco = {version = "0.4", path="../../../../pco"}
