name: Java Publish

on:
  release:
    types:
      - published

env:
  GROUP_ID: io/github/pcodec
  # enable LTO to reduce binary size (empirically by ~20%)
  RUSTFLAGS: "-C lto=true -C embed-bitcode=true -Zdylib-lto"

jobs:
  linux:
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu ]
        include:
          - target: x86_64-unknown-linux-gnu
            jni_target: linux-x86-64
          - target: aarch64-unknown-linux-gnu
            jni_target: linux-aarch64
    runs-on: ubuntu-latest
    if: contains(github.event.release.name, 'Java')
    steps:
      - uses: actions/checkout@v4
      - name: Set Rust version
        run: rustup override set nightly
      - name: Cross compilation tools
        run: cargo install cross
      - name: Build target dylibs
        run: cross build --release -p pco_java --target "${{ matrix.target }}"
      - name: Upload dynamic lib
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.jni_target }}
          path: target/${{ matrix.target }}/release/libpco_java.so

  publish:
    runs-on: ubuntu-latest
    needs: [ linux ]
    if: contains(github.event.release.name, 'Java')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Download dylibs to resources
        uses: actions/download-artifact@v4
        with:
          path: pco_java/src/main/resources/${{ env.GROUP_ID }}
      - name: DEBUG
        run: |
          ls
          ls pco_java
          ls pco_java/src/main/resources/
          ls pco_java/src/main/resources/${{ env.GROUP_ID }}
          ls pco_java/src/main/resources/${{ env.GROUP_ID }}/linux-aarch64
      - name: Publish package
        run: cd pco_java && mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
