name: Java Publish

on:
  release:
    types:
      - published

env:
  GROUP_ID: io/github/pcodec
  # enable LTO to reduce binary size (empirically by ~20%)
  RUSTFLAGS: "-C lto=true -C embed-bitcode=true -Zdylib-lto"

jobs:
  linux:
    runs-on: ubuntu-latest
    if: contains(github.event.release.name, 'Java')
    steps:
      - uses: actions/checkout@v4
      - name: Set Rust version
        run: rustup override set nightly
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build target dylibs into resources dir
        run: pco_java/build_for_all_targets.sh
      - name: Publish package
        run: cd pco_java && mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}