# taking some ideas from
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-rust

name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    # TODO: test each crate with minimum required rust and dependency versions?
    steps:
      - uses: actions/checkout@v4
      - name: Override Rust Version
        run: rustup override set "$(cat .github/rust-test-version)"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.1
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Test
        run: cargo test --all-features
      - name: Tests on aarch64
        run: cross test -p pco --target aarch64-unknown-linux-gnu --all-features
  quality:
    name: "Quality"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Override Rust Version
        run: |
          rustup override set "$(cat .github/rust-test-version)"
          rustup component add clippy rustfmt
      - name: Ensure formatted
        run: cargo fmt --check
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.1
      - name: Clippy
        run: cargo clippy --no-deps --all-features
  benchmarks:
    name: "Benchmarks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Override Rust Version
        run: rustup override set "$(cat .github/rust-test-version)"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.1
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed
      - name: Build benchmarks
        run: cargo codspeed build -p pco --features bench
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
